import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { BodyStatsProvider } from "@/contexts/BodyStatsContext";
import Navigation from "@/components/Navigation";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="de">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<BodyStatsProvider>
					<div className="min-h-screen bg-gray-100">
						<Navigation />
						<main className="container mx-auto px-4">{children}</main>
					</div>
				</BodyStatsProvider>
			</body>
		</html>
	);
}
